### ISSUE TITLE
Make the “debug” config accept psr-3 levels

### ISSUE THREAD

**Issue by Nyholm** [async-aws/aws#800]
I just had an idea. Not sure if it is good or not. 

I used the debug feature in one app recently. I love it, it helped me solve the problem. However, since it is outputting on the “debug” level I needed to lower my config for “fingers crossed handler”. 

I suggest that the following is all valid config for our “debug” config. 

debug: true // like now
debug: ‘error’ // will log on “error” level
debug: 300 // will log on “warning” level
debug: 0 // no debugging
debug: false // no debugging

The symfony bundle can validate the values, but we need the Configutation itself to validate, don’t we? Hm. Or maybe not.

**Comment by jderusse** [comment]
Good idea, user can declare their own service in the `logger:` config key (when undefined, it fallback to the the service `logger` defined by symfony). But we can provide an easy way to change the verbosity of the logger.

Maybe with an `logger_verbosity` (or `log_level`) config key. Which is more more explicite

**Comment by Nyholm** [comment]
But we log a few different things. Im currently only focusing on the debug log messages. I want to edit the log_level on those. That is why I thought adding these new values to the `debug` key. 

Are you saying we should add: `debug_log_level` instead?

**Comment by jderusse** [comment]
I'm not sure to understand. 
Couldn't it solved by `$logger->debug('my debug log message');` that are hidden by default and shown when user configure $logger->setLevel('DeBUG');` ?

**Comment by Nyholm** [comment]
Hm. 

My issue is/was that I have a fingers_crossed handler. It ignores all messages until some "error" happens. 
When I enabled "debug" in async AWS, I still wont see any log messages. So I need to change my config in the fingers_crossed handler too.

That is why I wanted to be lazy to add a way to configure log_level for the AsyncAws debug messages. 

However, What I think I should do is rather to configure the log channel for the logger I use with AsyncAws, that way I can control the fringers_crossed handler separately for all the other logs in the app.

**Comment by jderusse** [comment]
I wonder if this isn't a more generic issue for applications and not specific to AsyncAws.

> However, What I think I should do is rather to configure the log channel for the logger I use with AsyncAws, that way I can control the fringers_crossed handler separately for all the other logs in the app.

Good idea, I think this is the way to go. Maybe we can define this by default.

**Comment by Nyholm** [comment]
I dont think "channels" are supported by monolog. It is a feature in the Symfony Monolog bundle. 

We might want to add some config in AsyncAwsBundle, But I doubt we should... maybe just close this issue.

**Comment by stof** [comment]
At the monolog levels, channels are separate Logger instances (Monolog's Logger has a name, because of that), which might share handlers between them.

**Comment by stof** [comment]
To make this easy, a solution in AsyncAwsBundle would be to tag services using the logger with `<tag name="monolog.logger" channel="async_aws" />`,  so that a dedicated channel is used (and so can receive a custom config if necessary)

**Comment by Nyholm** [comment]
Thank you. I've added a PR in #810
